In [3]:
import pandas as pd
import numpy as np
data = pd.read_csv("weather_forecast_data.csv")
data.head()

   Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0    23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1    27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2    25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3    23.622080  74.367758    7.050551    67.255282   982.632013     rain
4    20.591370  96.858822    4.643921    47.676444   980.825142  no rain

In [21]:
features = ["Temperature","Humidity","Wind_Speed","Cloud_Cover","Pressure"]
x = data[features]
y = data["Rain"]

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.8, test_size = 0.2, random_state = 0)

In [6]:
x_train.shape

(2000, 5)

In [7]:
x.shape

(2500, 5)

In [8]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state = 1)
dt_model.fit(x_train, y_train)
y_pre = dt_model.predict(x_test)
pd.DataFrame({'y' : y_test, 'y_pre' : y_pre})

            y    y_pre
53       rain     rain
2391  no rain  no rain
2310  no rain  no rain
728   no rain  no rain
850   no rain  no rain
...       ...      ...
1810  no rain  no rain
2330  no rain  no rain
684   no rain  no rain
1674  no rain  no rain
2075     rain     rain

[500 rows x 2 columns]

In [9]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
rf_model = RandomForestClassifier(random_state = 1)
rf_model.fit(x_train, y_train)
y_pre = rf_model.predict(x_test)

In [10]:
x_test.head()

      Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure
53      12.551120  89.741453   14.528978    77.426560  1009.816343
2391    30.390440  51.909354    6.917295    38.347559  1012.205489
2310    25.521039  51.329992   12.867868     5.738705   981.850917
728     28.982061  81.031086    1.808901    39.773119  1035.152503
850     32.226499  30.573110    8.134406    45.148408  1016.007536

In [11]:
input = pd.DataFrame([[24.5, 70.333, 10.123, 90.111, 1100]], columns = ['Temperature', 'Humidity', 'Wind_Speed', 'Cloud_Cover', 'Pressure'])
rf_model.predict(input)

array(['rain'], dtype=object)